#!/bin/bash
# Comprehensive Render Hosting Setup Guide
# For Question Paper PDF Generator App

echo "=== Question Paper Generator - Render Setup Guide ==="
echo ""
echo "This guide will help you deploy the frontend and PDF server to Render.com"
echo ""

# Step 1: Frontend Setup
echo "STEP 1: DEPLOY FRONTEND TO RENDER"
echo "=================================="
echo ""
echo "1. Go to https://render.com and sign up with GitHub"
echo ""
echo "2. Create a new Web Service:"
echo "   - Connect your GitHub repository"
echo "   - Repository: your-repo/xmpaper-generator-app"
echo "   - Name: qgen-frontend"
echo "   - Environment: Node"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm install -g serve && serve -s dist"
echo "   - Plan: Free (or Starter)"
echo ""
echo "3. Add Environment Variables (in Render dashboard):"
echo "   Key: VITE_PDF_API_URL"
echo "   Value: https://qgen-pdf-server.onrender.com (replace with your PDF server URL)"
echo ""
echo "4. Click 'Create Web Service' and wait for deployment"
echo ""

# Step 2: PDF Server Setup
echo "STEP 2: DEPLOY PDF SERVER TO RENDER"
echo "===================================="
echo ""
echo "1. Create a new Web Service:"
echo "   - Connect to the same GitHub repository"
echo "   - Name: qgen-pdf-server"
echo "   - Root Directory: server"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free (or Starter)"
echo ""
echo "2. Add Environment Variables (in Render dashboard):"
echo "   NODE_ENV=production"
echo "   PORT=5001"
echo "   FRONTEND_URL=https://qgen-frontend.onrender.com (replace with your frontend URL)"
echo ""
echo "3. Click 'Create Web Service' and wait for deployment"
echo ""

# Step 3: Update Frontend Configuration
echo "STEP 3: UPDATE FRONTEND CONFIGURATION"
echo "====================================="
echo ""
echo "1. Update .env.production file:"
echo "   VITE_PDF_API_URL=https://qgen-pdf-server.onrender.com"
echo ""
echo "2. Push changes to GitHub:"
echo "   git add .env.production"
echo "   git commit -m 'Update PDF server URL for production'"
echo "   git push"
echo ""

# Step 4: Monitor Deployments
echo "STEP 4: MONITOR AND TEST"
echo "========================"
echo ""
echo "1. Check deployment status at: https://dashboard.render.com"
echo ""
echo "2. Test the application:"
echo "   - Frontend: https://qgen-frontend.onrender.com"
echo "   - PDF Server: https://qgen-pdf-server.onrender.com (should show API info)"
echo ""
echo "3. Test PDF generation:"
echo "   - Create a question paper in the app"
echo "   - Click 'PDF ডাউনলোড করুন' button"
echo "   - PDF should download successfully"
echo ""

# Step 5: Troubleshooting
echo "STEP 5: TROUBLESHOOTING"
echo "======================"
echo ""
echo "Common Issues:"
echo ""
echo "1. PDF Generation Fails:"
echo "   - Check PDF Server logs in Render dashboard"
echo "   - Verify CORS is enabled (should be automatic)"
echo "   - Ensure Puppeteer is properly installed"
echo ""
echo "2. CORS Errors:"
echo "   - Check Render environment variables"
echo "   - Verify FRONTEND_URL in PDF server is correct"
echo ""
echo "3. Service Not Found:"
echo "   - Check both services are deployed"
echo "   - Verify URLs in environment variables"
echo ""

echo ""
echo "==== SETUP COMPLETE ===="
